### ISSUE TITLE
Grest FMT Replacing CRLF to LF (Windows)

### ISSUE THREAD

**Issue by MaulanaR** [zahir-core/grest-cli#1]
Step - step reproduce issue: 
1. Buka Code editor (ex: **vscode / goland**)
2. Line-breaks File CRLF (sebelum menjalankan grest fmt)
![gambar](https://user-images.githubusercontent.com/16471471/163748287-33e810ec-e9b0-462b-875c-2299db54eac7.png)
3. Jalankan command **grest fmt**
4. Line-breaks File LF (Setelah menjalankan grest fmt)
![gambar](https://user-images.githubusercontent.com/16471471/163748394-01ab6958-3c2c-4817-9d67-ee6d76c3cb19.png)

Efek yang ditimbulkan : 
1. Source Control Git terlist banyak file, tetapi setelah dilihat hanya ada perubahan line-breaks (padahal tidak ada perubahan terkait logic/ code).
![gambar](https://user-images.githubusercontent.com/16471471/163748678-1189ed73-d825-4fdf-88a7-cd7c8102a0e6.png)

**Comment by zuamsyah** [comment]
Issuenya sama dengan yg di issuenya -> https://github.com/golang/go/issues/2242
alternatifnya bisa setting di text editornya
